### ISSUE TITLE
build error : CMake Error at build/voxblox/voxbloxConfig.cmake:27

### ISSUE THREAD

**Issue by xinanqiurobotics** [Kin-Zhang/dynablox#2]
When I compile the dynablox project, I encounter the following error:
![2024-08-07 10-22-58屏幕截图](https://github.com/user-attachments/assets/3ceaf833-4bc8-4165-b875-6f959641e5aa)
Initially, I thought it was because voxblox wasn't built. However, when I build voxblox, I encounter:
![2024-08-07 10-27-47屏幕截图](https://github.com/user-attachments/assets/94eb052d-a7fa-4cc2-a897-0e185685b05a)
I hope to get your help on this. Thank you very much!

**Comment by Ruyi0813** [comment]
Is this problem solved please, I'm having the same problem. Thanks!

**Comment by xinanqiurobotics** [comment]
您好，QXN已经收到您的邮件，感谢您的来件

**Comment by xinanqiurobotics** [comment]
> Is this problem solved please, I'm having the same problem. Thanks!
I'm very sorry; I haven't solved this problem yet either.

**Comment by Kin-Zhang** [comment]
Thanks for reporting this issue, I push a new commit to fix. please clean up/remove build folder then rebuild again. Let me know if the problem still exists.

Tested within a new env successfully:
![image](https://github.com/user-attachments/assets/4f2d2f6e-f5d2-4144-90c3-9a04a579d156)

**Comment by xinanqiurobotics** [comment]
您好，QXN已经收到您的邮件，感谢您的来件
